px update
portworx/dcos-commons pull request #123
Opened 2019-07-24 19:10 UTC by tusharraut1994

- Changed px default image to  : portworx/px-enterprise:2.0.3.7
- Changed px-lighthouse default image to : portworx/px-lighthouse:2.0.4
- Added advanced placement constraint options.

2019-07-24 20:47 UTC, disrani-px commented on frameworks/portworx/universe/config.json
> +			"default": "[[\"hostname\", \"UNIQUE\"]]",
Can you confirm this doesn't break upgrades? ie define a constraint with the currently released framework and then update to this version

2019-07-29 16:32 UTC, disrani-px approved these changes

2019-07-29 16:32 UTC, disrani-px commented on frameworks/portworx/universe/config.json
> +            "default": "portworx/px-enterprise:2.0.3.7"
Use `2.0.3.8`

2019-07-29 16:42 UTC, tusharrautOO7 commented on frameworks/portworx/universe/config.json
> +			"default": "[[\"hostname\", \"UNIQUE\"]]",
Verified upgrade, working as expected.
Deployed portworx service with old version with placement constraints : "placement_constraint": "hostname:LIKE:(70.0.86.175|70.0.86.181|70.0.86.184)"
- Once the px is ready added new node into DCOS cluster and then updated portworx service using command: `dcos portworx update start --package-version=stub-universe`
- Observed px node came on same nodes.

2019-07-29 16:42 UTC, tusharraut1994 commented on frameworks/portworx/universe/config.json
> +            "default": "portworx/px-enterprise:2.0.3.7"
Changed.

2019-07-30 17:49 UTC, piyush-nimbalkar requested changes

2019-07-30 17:49 UTC, piyush-nimbalkar commented on frameworks/portworx/universe/config.json
> +            "default": "portworx/px-enterprise:2.0.3.8"
We need to change the images in universe/resource.json as well.

2019-09-13 07:05 UTC, tusharraut1994 commented on frameworks/portworx/universe/config.json
> +            "default": "portworx/px-enterprise:2.0.3.8"
Changed

2021-03-22 06:08 UTC, closed without merging