px sdk update to mesosphere/dcos-commons-0.56.1
portworx/dcos-commons pull request #128
Opened 2019-08-02 12:13 UTC by tusharraut1994

2019-08-03 04:21 UTC, disrani-px requested changes
These commits are empty: 
https://github.com/portworx/dcos-commons/pull/128/commits/17d72dfd7ce695b885427db3b23610f779eb50ca
https://github.com/portworx/dcos-commons/pull/128/commits/2d2929ed9f1d6e72a745b3e60bb438cb1c880225
https://github.com/portworx/dcos-commons/pull/128/commits/139e6a2ead8cc09c16591b04b65c5075233e4665
https://github.com/portworx/dcos-commons/pull/128/commits/4ab8283ba5310d90b9ab9023e5f8186da5bd3c0e
https://github.com/portworx/dcos-commons/pull/128/commits/ef09a9c5be1bfb6fbed3956e4908e4caf406ed28
https://github.com/portworx/dcos-commons/pull/128/commits/2deb31c6d184f7427d277c8412060c8607afae12
https://github.com/portworx/dcos-commons/pull/128/commits/89bbde53a5d97ddbae2ce04b6401e4c8db2f71ed
https://github.com/portworx/dcos-commons/pull/128/commits/08ea635b32e301fd81c856db16fc1dba0d28078c
https://github.com/portworx/dcos-commons/pull/128/commits/27dbed3d91f85914cf2dd216af2ab94ed530b360
https://github.com/portworx/dcos-commons/pull/128/commits/23531df0855334c6db78971bdcd4b87b4586b282
https://github.com/portworx/dcos-commons/pull/128/commits/aa5af84c82cb3d6d36caa2a31679bc8c0307da69
https://github.com/portworx/dcos-commons/pull/128/commits/74a7583b575c03272721cb9e7e3149c8809803e8
https://github.com/portworx/dcos-commons/pull/128/commits/efe20fc391569421b3e77c82e5d98369d5c5421b
https://github.com/portworx/dcos-commons/pull/128/commits/f0589e59b030425103892dfc28e6c2c14213e1d6

This change has a merge conflict marker: https://github.com/portworx/dcos-commons/pull/128/commits/c6f6ab47a19d80d8dc05fe405bc019a4da37678a

Also remove the empty kafka commits

2019-08-03 04:21 UTC, disrani-px commented on sdk/scheduler/src/test/java/com/mesosphere/sdk/testutils/TestPodFactory.java
> +                //.addRootVolume(disk, TestConstants.CONTAINER_PATH)
Remove commented code

2019-08-03 04:21 UTC, disrani-px commented on frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java
> +    Assert.assertEquals(result.getSchedulerEnvironment().get("SERVICE_REGION"), null);
Undo this change

2019-08-03 04:21 UTC, disrani-px commented on sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategy.java
> -      // Note: We mark ALL dependencies (including inferred dependencies) because DependencyStrategyHelper doesn't
Don't remove comments

2019-08-03 04:21 UTC, disrani-px commented on tools/release_builder.py
> +        '''Add the '-beta' suffix to the package version if required'''
Don't need this change anymore

2019-08-03 04:21 UTC, disrani-px commented on frameworks/portworx/universe/marathon.json.mustache
> +    "TASK_FAILURE_TIMEOUT_MINUTES": "{{{service.task_failure_timeout_minutes}}}",
This change is missing the update in `Main.java` for where `TASK_FAILURE_TIMEOUT_MINUTES` is being used?
Commit 17bb8c03c9874140e29b2e7f6797c3275210d680 from px_1.3-0.40.5

2019-08-03 04:21 UTC, disrani-px commented on frameworks/elastic/src/main/dist/svc.yml
> +          set -ex
All the commands are missing `sudo chown {{FRAMEWORK_USER}} $MESOS_SANDBOX/container-path -R` which will cause the framework to fail

2019-08-03 04:21 UTC, disrani-px commented on testing/sdk_metrics.py
> +        "GET", "/system/v1/agent/{}/metrics/v0/containers/{}/app".format(agent_id, task_container_id), retry=False)
Undo commit 930f82fad9f850d40942edc1b4c4d09253f1aeb7, it's no longer required

2019-08-03 04:21 UTC, disrani-px commented on testing/sdk_metrics.py
> +    missing_metrics = []
Undo commit ae166cbca4dbcf39ea643ae4613d2a1a5a597daa, it is no longer required

2019-08-05 17:01 UTC, tusharraut1994 commented on tools/release_builder.py
> +        '''Add the '-beta' suffix to the package version if required'''
Changed.

2019-08-05 17:01 UTC, tusharraut1994 commented on sdk/scheduler/src/main/java/com/mesosphere/sdk/scheduler/plan/strategy/SerialStrategy.java
> -      // Note: We mark ALL dependencies (including inferred dependencies) because DependencyStrategyHelper doesn't
Added changes.

2019-08-05 17:02 UTC, tusharraut1994 commented on frameworks/elastic/src/test/java/com/mesosphere/sdk/elastic/scheduler/ServiceTest.java
> +    Assert.assertEquals(result.getSchedulerEnvironment().get("SERVICE_REGION"), null);
Changed.

2019-08-05 17:03 UTC, tusharraut1994 commented on testing/sdk_metrics.py
> +    missing_metrics = []
Done.

2019-08-05 17:06 UTC, tusharraut1994 commented on testing/sdk_metrics.py
> +        "GET", "/system/v1/agent/{}/metrics/v0/containers/{}/app".format(agent_id, task_container_id), retry=False)
Done.

2021-03-22 06:08 UTC, closed without merging