Adding dcos secrets config params
portworx/dcos-commons pull request #28
Opened 2018-03-25 22:32 UTC by piyush-nimbalkar

Also adding volume to start task resource such that it remains on the same node on restart. 
Observed it once that it moved to a different node on `force-restart deploy` plan.

2018-03-25 22:42 UTC, disrani-px requested changes

2018-03-25 22:42 UTC, disrani-px commented on frameworks/portworx/src/main/dist/svc.yml
> +        resource-set: px-resources
Using the same resource set causes problems when updating the image name. The install task tries to use the same reserved volume as the start task and keeps failing. 
Add a volume to both the resource sets, which should pin the tasks.

2018-03-25 22:47 UTC, piyush-nimbalkar commented on frameworks/portworx/src/main/dist/svc.yml
> +        resource-set: px-resources
okay, done

2018-03-26 20:16 UTC, disrani-px approved these changes
Just confirming, if the username/password changes just need to restart the "start" tasks, right?

2018-03-26 23:27 UTC, piyush-nimbalkar commented
Once we have restart service in start task, the env variables will get passed on to PX. Currently we do see the new env vars in the logs that DCOS populates.

2018-03-26 23:27 UTC, merged