[PTX-729] Fixed dcos cassandra pytests portworx volume cleanup
portworx/dcos-commons pull request #82
Opened 2018-10-15 11:24 UTC by jitupawar22

Added a portworx-cassandra cleanup routine in cassandra sdk_install.
    With this fix cassandra portworx volumes present on any agent gets deleted after every category of test run.

2018-10-15 18:06 UTC, piyush-nimbalkar approved these changes

2018-10-15 18:06 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +#Portworx specific cleanups are done here.
nit: put space after all the comments #

2018-10-15 18:06 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +    #Call portworks specific cleanup routine at the end.
nit: *portworx

2018-10-16 19:13 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +        'for vol in `pxctl v l | grep Cassandra | cut -f 2`; do pxctl v d -f $vol; done', 'vagrant','/ssh/key')
We should ideally delete all portworx volumes here, instead of deleting only cassandra volumes.
Will be handy when we add tests for other frameworks.

2018-10-16 19:13 UTC, piyush-nimbalkar approved these changes
You can merge this for now and update the clean up function later as you make more tests pass and add new ones.

2018-10-16 19:27 UTC, disrani-px requested changes

2018-10-16 19:27 UTC, disrani-px commented on testing/sdk_install.py
> +        'for vol in `pxctl v l | grep Cassandra | cut -f 2`; do pxctl v d -f $vol; done', 'vagrant','/ssh/key')
Please use jq here or get the output in json and unmarshal it into some kind of pythin structure instead of using 'cut'

2018-10-17 20:28 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +    exit_status, output_agent = shakedown.run_command_on_agent(agents[0]['hostname'],
print error message and return if the command fails
while deleting print the error message stating why the volume delete failed, but continue to delete the rest of the volumes

2018-10-18 20:37 UTC, piyush-nimbalkar approved these changes

2018-10-19 02:19 UTC, disrani-px approved these changes

2018-10-19 02:43 UTC, merged