Added pytest based tests for portworx framework
portworx/dcos-commons pull request #90
Opened 2018-11-20 06:48 UTC by jitupawar22

For https://portworx.atlassian.net/browse/PTX-787
Following functionalities implemented-
    Indtall, Uninstall, upgrade, cleanup, check service health.
Note that the cleanup script is place holder in this commit.
We need to improve overall post uninstall cleanup for portworx.

2018-11-26 05:15 UTC, piyush-nimbalkar requested changes

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/scripts/px_dcos_cleanup.sh
> +px_services=`dcos service --inactive | grep -v "ACTIVE  TASKS  CPU" | grep "portworx" | awk '{print $7}'`
Instead of this use jq to extract the ID
`dcos service --inactive --json | jq -r '.[] | select(.name=="portworx") | .id'`

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/config.py
> +DEFAULT_CASSANDRA_TIMEOUT = 600
Remove this

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/config.py
> +DEFAULT_NODE_ADDRESS = os.getenv('PORTWORX_NODE_ADDRESS', sdk_hosts.autoip_host(SERVICE_NAME, 'node-0-server'))
Is this needed?
If yes let's use the vip host instead of pointing to zeroth node. Anyway `node-0-server` is incorrect , it should have been `portworx-0-install`

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/config.py
> +PX_NODE_OPTIONS = { "node": { "portworx_options": "-a -x mesos -d enp0s8 -m enp0s8",
Can we take these individual options as env variables and combine them in the config?
At least kvdb servers should not be committed in the code.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/conftest.py
> +    yield from sdk_security.security_session('portworx')
Can we use the SERVICE_NAME instead of `portworx` here?

2018-11-26 05:15 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +    for i in range(len(agents)):
This is a vagrant specific cleanup routine and will not work for all deployments. For instance if someone wants to run a sanity test on AWS, this will not work.
May be take the username and key from env vars.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +        exit_status, output_agent = shakedown.run_command_on_agent('192.168.65.131', cmd, 'vagrant','/ssh/key')
Use `agents[i]['hostname']`

2018-11-26 05:15 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +            'pxctl -j v l', 'vagrant','/ssh/key')
Same as below comment, don't hard code the username and ssh key.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +# Here are tests for variour update options available for portworx.
*various

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +def test_update_service_node():
*test_update_node_count would be more precise

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +    update_options = {
nit:  It this method is just forming the options, you could combine it with the actual test method. Same for below tests.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +        json.dump(options, f)
Here we are sending only the changed options. Does the update work without sending rest of the existing options? Does it auto merge?
Haven't tried it before myself.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    shakedown.service_healthy(config.SERVICE_NAME)
This seems to be checking that the tasks are healthy and in running state.
Can we also check status of portworx service and px status?

2018-11-26 05:15 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +    _portworx_volcleanup()
I feel we should call the portworx volume cleanup from the tests wherever we are uninstalling the framework, because it does not make much sense to do volume cleanup on portworx framework cleanup itself.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +def _portworx_volcleanup():
nit: `_portworx_vol_cleanup`?

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    assert sdk_install.portworx_cleanup() == 0
Instead of asserting on the return status, just raise an exception on failure just like other sdk functions (install, uninstall, etc)

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +# Upgrade portworx
*Upgrade portworx framework from released version

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +def update_service(service: dict, options: dict):
where do we use the service?

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.SERVICE_NAME)
Do we need to always reinstall the framework for changing options?
May be we can pass boolean which tells us to optionally uninstall? It will save us some time in test runs.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.get_foldered_service_name())
Looks like the `test_upgrade` method is already doing an uninstall of the service. We don't need to do it explicitly.

2018-11-26 05:15 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    sdk_upgrade.test_upgrade(
Does this install the universe version and then upgrade to the `stub-universe` version?
When it does so, will the universe repo always remain on the top? Other tests that do an install, will they use the universe package or the stub-universe package?

2018-11-26 06:55 UTC, jitupawar22 commented on frameworks/portworx/tests/config.py
> +DEFAULT_NODE_ADDRESS = os.getenv('PORTWORX_NODE_ADDRESS', sdk_hosts.autoip_host(SERVICE_NAME, 'node-0-server'))
No now but, will be needed in future.  Changing name to portworx-0-install

2018-11-26 18:43 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/config.py
> +DEFAULT_NODE_ADDRESS = os.getenv('PORTWORX_NODE_ADDRESS', sdk_hosts.autoip_host(SERVICE_NAME, 'node-0-server'))
If you don't need to talk to a specific node, I would recommend using `vip_host(SERVICE_NAME, 'api')` which is like a load balancer for portworx nodes.

2018-12-06 11:13 UTC, jitupawar22 commented on frameworks/portworx/tests/test_update_px_service.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.SERVICE_NAME)
No we don't need to uninstall every time. 
That uninstall don't get called every time. That gets call only first time before fresh installation.

2018-12-07 11:28 UTC, jitupawar22 commented on frameworks/portworx/tests/test_sanity.py
> +    sdk_upgrade.test_upgrade(
It use universe  package and then upgrade to stub-universe. 
Other tests from automation always use stub-universe.

2018-12-10 05:19 UTC, jitupawar22 commented on frameworks/portworx/tests/config.py
> +DEFAULT_NODE_ADDRESS = os.getenv('PORTWORX_NODE_ADDRESS', sdk_hosts.autoip_host(SERVICE_NAME, 'node-0-server'))
Sure, Will consider using vip_host(SERVICE_NAME, 'api'). removing this now.

2018-12-10 05:24 UTC, jitupawar22 commented on testing/sdk_install.py
> +    for i in range(len(agents)):
Yeah good catch. We need to consider cleanups for all cluster types.

2018-12-10 05:32 UTC, jitupawar22 commented on frameworks/portworx/tests/test_update_px_service.py
> +        json.dump(options, f)
Yes, the update works without sending rest of the existing options, it does auto merge.

2018-12-10 05:34 UTC, jitupawar22 commented on frameworks/portworx/tests/test_sanity.py
> +    shakedown.service_healthy(config.SERVICE_NAME)
That's right, we can additionally verify that as well.

2018-12-10 05:45 UTC, jitupawar22 commented on testing/sdk_install.py
> +    _portworx_volcleanup()
To avoid calls from multiple places I considered calling it at the end of uninstall function itself. 
But I now I am also thinking that portworx specific cleanups should be outside from common framework cleanups.

2018-12-11 23:50 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/config.py
> +DEFAULT_NODE_ADDRESS = os.getenv('PORTWORX_NODE_ADDRESS', sdk_hosts.autoip_host(SERVICE_NAME, 'node-0-server'))
Remove it or change it to `vip_host`

2018-12-11 23:50 UTC, piyush-nimbalkar commented on testing/sdk_install.py
> +    for i in range(len(agents)):
Create a ticket for this and put it in next PR.

2018-12-11 23:51 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    shakedown.service_healthy(config.SERVICE_NAME)
We should verify that, otherwise it is not a complete test. We can't just rely on the framework install being successful, we have to check if Portworx cluster is up and running as well.

2018-12-11 23:53 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.get_foldered_service_name())
Do we need to need to the uninstall here? Isn't `test_upgrade` already doing it?

2018-12-11 23:54 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.SERVICE_NAME)
The `portworx_service` method seems to be called from all the tests. How does this not get triggered every time?

2018-12-11 23:55 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    assert sdk_install.portworx_cleanup() == 0
Can you address this?

2018-12-12 00:02 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.get_foldered_service_name())
My bad, I see it is commented. Can you just remove the line?

2018-12-12 00:14 UTC, piyush-nimbalkar requested changes

2018-12-12 00:14 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +    update_service(update_options)
We should verify the specific changes that these options are going to bring in Portworx. For instance,
Verify the count of Portworx nodes has actually changed to 3.
Verify that portworx is actually upgraded to the given image version.
Verify lighthouse in enabled and reachable (do a curl and check)
Verify lighthouse is not running.
and so on

2018-12-12 00:14 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_update_px_service.py
> +def test_update_enable_etcd():
Can you verify manually if changing the etcd is allowed once the framework is deployed? If yes what happens to Portworx in that case? Portworx should stop functioning because its kvdb itself changes.

2018-12-12 05:12 UTC, jitupawar22 commented on frameworks/portworx/tests/test_update_px_service.py
> +def test_update_enable_etcd():
It is allowed to change etcd once the framework is deployed - Actually it should not allowed. 
Yes manually I saw portworx stops functioning after changing etcd .

2018-12-12 05:21 UTC, jitupawar22 commented on frameworks/portworx/tests/test_update_px_service.py
> +    update_service(update_options)
The pytest sdk internally verify few things for example-
if we change node from 1 to 3 the test framework waits till 3 nodes comes up and healthy, if it fails to come up before timeout then it fails the test. 
same goes with lighthouse node. For upgrade image also it destroy all nodes and waits for installation with updated image on all nodes. If existing nodes does not destroy or nodes with new image does not come up then the framework fails the test. 
I agree that we should do portworx specific verification those not get covered from SDK.

2018-12-17 06:08 UTC, jitupawar22 commented on frameworks/portworx/tests/test_update_px_service.py
> +    sdk_install.uninstall(config.PACKAGE_NAME, config.SERVICE_NAME)
That is because we have marked portworx_service as  @pytest.fixture. It gets call only once for pytest session.
And at teardown it invokes the cleanup code wrote in "finally:". 
I have made calls from every test such that user can have flexibility to run any individual test as well.

2018-12-17 07:29 UTC, jitupawar22 commented on testing/sdk_install.py
> +    for i in range(len(agents)):
Created PXT-831

2018-12-19 11:27 UTC, jitupawar22 commented on frameworks/portworx/tests/test_update_px_service.py
> +    update_service(update_options)
Updated PR with necessary verification those are not get addressed through pytest SDK.

2019-01-04 19:20 UTC, piyush-nimbalkar approved these changes
This looks good to me. 
Address the minor comments and merge it in.

2019-01-04 19:20 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/px_utils.py
> +    while count < config.PX_TIMEOUT:
nit: Just do a time comparison here instead of keeping a count. Record a time before the while loop and check  
`start + PX_TIMEOUT < datetime.now()`

2019-01-04 19:20 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/px_utils.py
> +    if True != is_int(px_node_count):
nit: simplify -
`if not is_int(px_node_count):`

2019-01-04 19:20 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    if 2 != px_status:
Here you could use
`assert px_status == 2`

same for below tests

2019-01-04 19:20 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +# Verify suspend and resume portworx service
nit: new line here

2019-01-04 19:20 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/test_sanity.py
> +    if sdk_install.portworx_cleanup() != 0:
What I meant was that portworx_cleanup() method should raise an exception on failure instead of returning a code. Here the code will be just calling `sdk_install.portworx_cleanup()`

2019-01-09 20:06 UTC, merged

2019-01-10 21:14 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/px_utils.py
> +    cmd = "portworx volume list | jq '.[] | select(.locator.name == \"" + vol_name +"\") | .spec.size'"
Could have done a volume inspect, right?

2019-01-10 21:14 UTC, piyush-nimbalkar commented on frameworks/portworx/tests/px_utils.py
> +    cmd = "node ssh  \"sudo systemctl stop portworx\" --user=" + config.PX_AGENT_USER + " --mesos-id=" + agent_id + " --option StrictHostKeyChecking=no"
could wrap this in a method which takes the agent user and agent id
eg. 
```
run(cmd, user=config.PX_AGENT_USER, agent_id=agent_id)
```